### ISSUE TITLE
[Documentation] simple question on --model_type option 

### ISSUE THREAD

**Issue by j2ho** [seoklab/alphafold#3]
### Describe the bug

In README under monomer folding, it says to use the following commmand (for example) 

```
alphafold \
  --model_type = monomer \
  monomer.fasta
```

however, when looking at the following error log, monomer option doesn't seem to exist anymore. 

```
absl.flags._exceptions.IllegalFlagValueError: flag --model_type=monomer: value should be one of <normal|ptm|multimer|casp14>
```

### Bug on which cluster?

cluster3

### Additional context

not really a huge issue (i just used the normal option instead) 
but just issued this bug for others just in case..!

**Comment by jnooree** [comment]
It's not actually a bug but a problem in the documentation. Thanks for the report!
